# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

windowrule {
    name = vesktop
    match:class = vesktop
    workspace = special
}

windowrule {
    name = pipes.sh
    match:class = kitty
    match:title = pipes.sh
    float = true
}

windowrule {
    name = cava
    match:class = kitty
    match:title = cava
    float = true
}

windowrule {
    name = btm
    #match:class = kitty
    match:title = btm
    float = on
}
